### ISSUE TITLE
TypeError: Could not handle Node of kind: 'JSDocDeprecatedTag'

### ISSUE THREAD

**Issue by nakagawa424** [wessberg/rollup-plugin-ts#111]
- Version:
- Rollup Version:
- Operating System and version (if applicable):
- Node Version (if applicable):
- Does it work with `tsc` (if applicable):

**Comment by wessberg** [comment]
Hi there. Thanks for submitting this issue. Thankfully it was intuitively obvious for me from the title what was going on, but I would encourage you to generally provide more information in the future, as I also request in the issue template that you left empty. It has been fixed as part of [v1.3.3](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.3.3)

**Comment by nakagawa424** [comment]
waiting for npm publish

**Comment by wessberg** [comment]
It has been published already! version 1.3.3 of `@wessberg/rollup-plugin-ts` on npm

**Comment by nakagawa424** [comment]
Oops, your official one was https://www.npmjs.com/package/@wessberg/rollup-plugin-ts, not https://www.npmjs.com/package/rollup-plugin-ts

Thanx

**Comment by asturur** [comment]
This is happening today for me with verison 3.0.2

```
[!] (plugin Typescript) TypeError: Could not handle Node of kind: 'JSDocOverrideTag'
    at executeCloneNode (file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:790:8)
    at nextNode (file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:318:16)
    at file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:366:39
    at Array.map (<anonymous>)
    at nextNodes (file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:366:27)
    at Object.nextNodes (file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:307:84)
    at cloneJsDoc (file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-js-doc-comment.ts:9:48)
    at executeCloneNode (file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:713:10)
    at nextNode (file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:318:16)
    at file:///Users/abogazzi/fabric.js/node_modules/ts-clone-node/src/clone-node/clone-node.ts:366:39
```

And i m not sure what is causing it.
It happens if i try to use exports in my entrypoint for build
