### ISSUE TITLE
Typescript 4.5.2 breaks rollup-plugin-ts

### ISSUE THREAD

**Issue by bcoe** [wessberg/rollup-plugin-ts#158]
- Version: 1.3.14
- Rollup Version: 2.60.0
- Operating System and version (if applicable): N/A
- Node Version (if applicable): N/A
- Does it work with `tsc` (if applicable): Yes.

### Reproduction

run yargs test suite with latest version of typescript.

### Expected Behavior

CJS output file created.

### Actual Behavior

```bash
(!) Circular dependency
lib/yargs-factory.ts -> lib/command.ts -> lib/yargs-factory.ts
[!] (plugin Typescript) TypeError: Cannot read property 'text' of undefined
TypeError: Cannot read property 'text' of undefined
    at getExportedSymbolFromExportSpecifier (/Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/util/create-export-specifier-from-name-and-modifiers.ts:49:35)
    at createExportSpecifierFromNameAndModifiers (/Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/util/create-export-specifier-from-name-and-modifiers.ts:83:20)
    at visitTypeAliasDeclaration (/Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/transformers/track-exports-transformer/visitor/visit-type-alias-declaration.ts:10:27)
    at visitNode (/Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/transformers/track-exports-transformer/visitor/visit-node.ts:29:10)
    at /Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/transformers/track-exports-transformer/track-exports-transformer.ts:19:5
    at visitNodes (/Users/benjamincoe/oss/yargs/node_modules/typescript/lib/typescript.js:29880:30)
    at Object.forEachChild (/Users/benjamincoe/oss/yargs/node_modules/typescript/lib/typescript.js:30122:24)
    at Object.childContinuation (/Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/transformers/track-exports-transformer/track-exports-transformer.ts:18:15)
    at visitModuleDeclaration (/Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/transformers/track-exports-transformer/visitor/visit-module-declaration.ts:9:41)
    at visitNode$c (/Users/benjamincoe/oss/yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/transformers/track-exports-transformer/visitor/visit-node.ts:31:10)
```

Thanks for the great library 👍

**Comment by wessberg** [comment]
Hey there,

TypeScript 4.5 support was added in [v2.0.2](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v2.0.2).

Please be aware of the breaking changes described in the v2.0.0 release notes.

**Comment by bcoe** [comment]
@wessberg `v2` works like a charm, the problem was that I was on `@wessberg/rollup-plugin-ts`, which I'm guessing was what this was released under historically?

Thanks for the great library.

**Comment by wessberg** [comment]
Thanks! Yeah, it was deprecated some time ago when I decided to drop the `@wessberg` scope. When you install the deprecated package you'll get warnings from your terminal with your package manager of choice with a message saying that it is advised to move to just `rollup-plugin-ts`
