### ISSUE TITLE
(plugin Typescript) TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by rexkenley** [wessberg/rollup-plugin-ts#160]
- Version: 1.4.7
- Rollup Version: 2.58
- Operating System and version (if applicable): windows 10
- Node Version (if applicable): 16.13

### Reproduction
https://github.com/rexkenley/rollupError

### Expected Behavior
Build the library

### Actual Behavior
[!] (plugin Typescript) TypeError: Cannot read properties of undefined (reading 'text')
TypeError: Cannot read properties of undefined (reading 'text')
    at getExportedSymbolFromExportSpecifier (C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\util\create-export-specifier-from-name-and-modifiers.ts:48:35)
    at createExportSpecifierFromNameAndModifiers (C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\util\create-export-specifier-from-name-and-modifiers.ts:82:20)
    at visitEnumDeclaration (C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-enum-declaration.ts:10:27)
    at visitNode (C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-node.ts:25:10)
    at C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\track-exports-transformer.ts:19:5
    at visitNodes (C:\vs\GIT\PowerFramework360\node_modules\typescript\lib\typescript.js:29880:30)
    at Object.forEachChild (C:\vs\GIT\PowerFramework360\node_modules\typescript\lib\typescript.js:30122:24)
    at Object.childContinuation (C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\track-exports-transformer.ts:18:15)
    at visitModuleDeclaration (C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-module-declaration.ts:9:41)
    at visitNode$c (C:\vs\GIT\PowerFramework360\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-node.ts:31:10)

**Comment by wessberg** [comment]
Hi there,

This is caused by sitting on an older version of `rollup-plugin-ts` not compatible with TypeScript v4.4 and up.
To resolve the issue, please update to the latest version, which is [v2.0.4](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v2.0.4)

**Comment by rexkenley** [comment]
Thank you for the quick response.
