### ISSUE TITLE
Update 1.1.74 broke the build

### ISSUE THREAD

**Issue by zhaparoff** [wessberg/rollup-plugin-ts#47]
Hello,

After updating from 1.1.73 to latest my builds are not working anymore.
I've checked all versions down to 1.1.73, and it seems like issue was introduced in 1.1.74.

Running `rollup -c` fails with the following error:
```
[!] (plugin Typescript) ReferenceError: Expected exported symbols for other module: 'C:/_Work/Code/GitHub/xrm-alerts/src/ts/alert.ts' to be present
ReferenceError: Expected exported symbols for other module: 'C:/_Work/Code/GitHub/xrm-alerts/src/ts/alert.ts' to be present
    at assertDefined (C:\_Work\Code\GitHub\xrm-alerts\node_modules\@wessberg\rollup-plugin-ts\src\util\assert-defined\assert-defined.ts:3:9)
    at visitExportedSymbol (C:\_Work\Code\GitHub\xrm-alerts\node_modules\@wessberg\rollup-plugin-ts\src\service\transformer\declaration-bundler\modularizer\visitor\visit-exported-symbol.ts:215:2)
    at C:\_Work\Code\GitHub\xrm-alerts\node_modules\@wessberg\rollup-plugin-ts\src\service\transformer\declaration-bundler\modularizer\modularizer.ts:58:11
    at transformation (C:\_Work\Code\GitHub\xrm-alerts\node_modules\typescript\lib\typescript.js:89262:24)
    at Object.map (C:\_Work\Code\GitHub\xrm-alerts\node_modules\typescript\lib\typescript.js:543:29)
    at Object.transformNodes (C:\_Work\Code\GitHub\xrm-alerts\node_modules\typescript\lib\typescript.js:89269:30)
    at Object.transform (C:\_Work\Code\GitHub\xrm-alerts\node_modules\typescript\lib\typescript.js:132581:25)
    at transform (C:\_Work\Code\GitHub\xrm-alerts\node_modules\@wessberg\rollup-plugin-ts\src\declaration\bundle-declarations-for-chunk.ts:12:17)
    at emitDeclarations (C:\_Work\Code\GitHub\xrm-alerts\node_modules\@wessberg\rollup-plugin-ts\src\declaration\emit-declarations.ts:184:27)
    at Object.generateBundle (C:\_Work\Code\GitHub\xrm-alerts\node_modules\@wessberg\rollup-plugin-ts\src\plugin\typescript-plugin.ts:430:5)
```

node: `v13.1.0` and `v12.13.0`
OS: Win 10 x64 build 1903
[package.json](https://github.com/zhaparoff/xrm-alerts/blob/master/package.json)
[rollup.config.js](https://github.com/zhaparoff/xrm-alerts/blob/master/rollup.config.js)
[tsconfig.json](https://github.com/zhaparoff/xrm-alerts/blob/master/tsconfig.json)

**Comment by wessberg** [comment]
Hi there. Sorry about that. This is due to a regression in Windows introduced in v1.1.74. It has been fixed and released as part of [v1.1.78](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.1.78)

**Comment by orokanasaru** [comment]
@wessberg, this appears to be broken again in 1.1.80

**Comment by wessberg** [comment]
@orokanasaru, do you have a simple repro I can take a look at and set up a test case for? This is strictly Windows-related, and as it is not my primary development environment, its important that I have test cases that catches any regressions before they happen. Currently, all tests are passing on Windows, but there may be a bug somewhere

**Comment by orokanasaru** [comment]
Unfortunately, I don't have any shareable repro at the moment. I can try to get one, but it's unlikely to happen in the next couple of weeks.
