### ISSUE TITLE
Error when modifying an imported module in watch mode

### ISSUE THREAD

**Issue by Asha20** [wessberg/rollup-plugin-ts#63]
Whenever I try to modify a file that isn't the entry file, but rather is being imported into the entry file, I get the following error:

```
[!] (plugin Typescript) TypeError: Cannot read property 'fileName' of undefined
TypeError: Cannot read property 'fileName' of undefined
    at /home/asha/rollup-ts-error/node_modules/@wessberg/rollup-plugin-ts/dist/cjs/index.js:3147:71
    at transformation (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:89306:24)
    at transformRoot (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:89326:82)
    at Object.map (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:543:29)
    at Object.transformNodes (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:89313:30)
    at emitDeclarationFileOrBundle (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:89891:43)
    at emitSourceFileOrBundle (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:89800:13)
    at forEachEmittedFile (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:89542:30)
    at Object.emitFiles (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:89780:9)
    at emitWorker (/home/asha/rollup-ts-error/node_modules/typescript/lib/typescript.js:95796:33)
```

I've created a [quick repository with the minimal reproduction of the error](https://gitlab.com/Asha20/rollup-plugin-ts-error). Here are the steps to reproduce the error after cloning the repo and installing the dependencies:

1. Run the `watch` script inside `package.json`. Notice how it compiles successfully on the first run.
2. Modify the `src/main.ts` file, AKA the entry file. It should re-compile successfully after each change.
3. Modify the `src/assert.ts` file, AKA the imported file. Making any change at all to the file should always result in the error above instead of re-compiling successfully.

If it matters, I'm running this code on Ubuntu 16.04, Node version 12.5.0. I've tried using both PNPM and NPM, but the error still persists. I think I might have used this plugin some 2 or 3 months ago without running into this error, but sadly I don't have the code anymore so I can't check what version it was of the plugin that didn't have the error.

**Comment by wessberg** [comment]
This is fixed and will be part of the next patch release

**Comment by Asha20** [comment]
Awesome; thanks for all your hard work on the plugin!

**Comment by wessberg** [comment]
Fixed in [v.1.2.2](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.2)
